apiVersion: kyverno.io/v1                               # Versão da API que define uma política
kind: ClusterPolicy                                     # Tipo de política que estamos definindo
metadata:                                               # Metadados da política
  name: allow-trusted-registry-except-no-chainguard     # Nome da política
spec:                                                   # Especificações da política
  validationFailureAction: enforce                      # Ação que será tomada em caso de falha na validação
  rules:                                                # Regras da política
  - name: trusted-registry-except-no-chainguard         # Nome da regra
    match:                                              # Condições para aplicar a regra
      resources:                                        # Recursos que serão validados
        kinds:                                          # Tipos de recursos que serão validados
        - Pod                                           # Tipo de recurso que será validado
    exclude:                                            # Exclusão de recursos
      resources:                                        # Recursos que serão excluídos
        namespaces:                                     # Namespaces que serão excluídos
        - no-chainguards                                # Nome do namespace que será excluído
    validate:                                           # Validação que será aplicada
      message: "Image is not from trusted registry"     # Mensagem de erro
      pattern:                                          # Padrão que será validado
        spec:                                           # Especificações do recurso
          containers:                                   # Containers que serão validados
          - image: "cgr.dev/chainguard/*"               # Imagem que será validada