apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: locust-giropops
spec:
  rules:
  - host: locust-giropops.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: locust-giropops
            port:
              number: 80